CREATE TABLE IF NOT EXISTS SIMULADOR.TRANSFERENCIA (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ESTORNO BIT NOT NULL DEFAULT 0,
  EXECUTADA BIT NOT NULL DEFAULT 0,
  DATA_TRANSFERENCIA TIMESTAMP NOT NULL,
  VALOR DECIMAL(19,5) NOT NULL,
  DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  TRANSFERENCIA_ESTORNADA_FK INT,
  CONTA_ORIGEM_FK INT NOT NULL,
  CONTA_DESTINO_FK INT NOT NULL,
  FOREIGN KEY (TRANSFERENCIA_ESTORNADA_FK) REFERENCES SIMULADOR.TRANSFERENCIA(ID),
  FOREIGN KEY (CONTA_ORIGEM_FK) REFERENCES SIMULADOR.CONTA(ID),
  FOREIGN KEY (CONTA_DESTINO_FK) REFERENCES SIMULADOR.CONTA(ID)
);