CREATE TABLE IF NOT EXISTS SIMULADOR.CONTA (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  AGENCIA VARCHAR(10) NOT NULL,
  NUMERO VARCHAR(10) NOT NULL,
  DIGITO VARCHAR(2) NOT NULL,
  BANCO_FK INT NOT NULL,
  FOREIGN KEY (BANCO_FK) REFERENCES SIMULADOR.BANCO(ID)
);