CREATE TABLE IF NOT EXISTS SIMULADOR.MOVIMENTACAO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TIPO INT NOT NULL,
  DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  VALOR DECIMAL(19,5) NOT NULL,
  CONTA_FK INT NOT NULL,
  FOREIGN KEY (CONTA_FK) REFERENCES SIMULADOR.CONTA(ID)
);
